# Generated by Django 3.2.7 on 2021-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabaritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabarito',
            name='acertadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gabarito',
            name='corrigidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gabarito',
            name='feitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
